"""followers

Revision ID: 95239f2145e3
Revises: b763d7de9535
Create Date: 2018-03-28 11:12:08.883339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95239f2145e3'
down_revision = 'b763d7de9535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
